services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64     # native cho M1
    container_name: backend_stackoverflow_app
    env_file: .env.docker     # <— dùng env dành cho container
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  mongo:
    image: mongo:6
    platform: linux/arm64
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    platform: linux/arm64
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  # đặt tên cố định để TRÁNH mất data khi đổi project name
  mongo_data:
    name: backend_stackoverflow_mongo_data

